version: '3'

services:
  web:
    build: ./ecommerce
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ecommerce/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./envs/.env
    depends_on:
      - postgres
      - mailcatcher
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres-user
      POSTGRES_DB: store_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
