# Generated by Django 3.2.16 on 2022-11-16 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='accounts.appuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(max_length=300),
        ),
    ]
