# Generated by Django 3.2.16 on 2022-11-12 18:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('item_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('item_strength', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(200)])),
                ('item_dexterity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(200)])),
                ('item_vitality', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(200)])),
                ('item_intellect', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(200)])),
                ('item_description', models.TextField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
