# Generated by Django 3.2.16 on 2022-11-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_newitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='body_part',
            field=models.CharField(choices=[('europe', 'Europe'), ('asia_pacific', 'Asia/Pacific'), ('north_america', 'North America')], default=1, max_length=13),
            preserve_default=False,
        ),
    ]
