# Generated by Django 3.2.16 on 2022-11-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_body_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='body_part',
        ),
        migrations.AddField(
            model_name='item',
            name='armor_piece',
            field=models.CharField(choices=[('helm', 'Helm'), ('armor', 'Armor'), ('shoulders', 'Shoulders'), ('gloves', 'Gloves'), ('boots', 'Boots')], default=1, max_length=9),
            preserve_default=False,
        ),
    ]
