# Generated by Django 3.2.16 on 2022-11-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20221112_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_description',
        ),
        migrations.AddField(
            model_name='item',
            name='item_short_description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='armor_piece',
            field=models.CharField(choices=[('helm', 'Helm'), ('armor', 'Armor'), ('gloves', 'Gloves'), ('boots', 'Boots'), ('weapon', 'Weapon'), ('shield', 'Shield')], max_length=6),
        ),
    ]
