# Generated by Django 3.2.16 on 2022-12-06 14:45

import django.core.validators
from django.db import migrations, models
import ecommerce.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_appuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(error_messages={'max_length': 'Username must be a maximum of 20 characters.', 'min_length': 'Username must be at least 2 characters long.'}, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2), ecommerce.accounts.validators.username_validator]),
        ),
    ]
