# Generated by Django 3.2.16 on 2022-11-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order_transaction',
        ),
    ]
