# Generated by Django 3.2.16 on 2022-11-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
