# Generated by Django 3.2.16 on 2022-11-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
