# Generated by Django 3.2.16 on 2022-11-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='order',
            new_name='cart',
        ),
    ]
