# Generated by Django 3.2.16 on 2022-11-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_order_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='order',
            new_name='cart',
        ),
    ]
