# Generated by Django 3.2.16 on 2022-11-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rename_order_shippingaddress_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='cart',
            new_name='order',
        ),
    ]
