# Generated by Django 3.2.16 on 2022-11-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_rename_cart_shippingaddress_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_transaction',
        ),
    ]
