# Generated by Django 3.2.16 on 2022-12-01 16:56

import django.core.validators
from django.db import migrations, models
import ecommerce.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(2), ecommerce.core.validators.validate_letters]),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(2), ecommerce.core.validators.validate_letters]),
        ),
    ]
