# Generated by Django 3.2.16 on 2022-12-02 16:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ecommerce.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0025_auto_20221201_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), ecommerce.accounts.validators.validate_letters])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), ecommerce.accounts.validators.validate_letters])),
                ('massage', models.TextField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
