# Generated by Django 3.2.16 on 2022-12-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='massage_checked',
            field=models.BooleanField(default=False),
        ),
    ]
