# Generated by Django 3.2.16 on 2022-12-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_rename_shippingaddress_shippinginfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippinginfo',
            old_name='order',
            new_name='cart',
        ),
    ]
