# Generated by Django 4.1.3 on 2022-12-07 12:00

import django.core.validators
from django.db import migrations, models
import ecommerce.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_contactus_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), ecommerce.core.validators.validate_letters]),
        ),
    ]
