# Generated by Django 4.1.3 on 2022-12-09 09:53

import django.core.validators
from django.db import migrations, models
import ecommerce.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_contactus_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='massage',
            field=models.TextField(max_length=250, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), ecommerce.core.validators.validate_letters]),
        ),
    ]
