# Generated by Django 4.1.3 on 2022-12-17 16:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_contactus_massage_alter_contactus_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
